
defaults: &defaults
  adapter: mongodb
  host:    localhost
  # slaves:
  #  - host: slave1.local
  #    port: 27018

development:
  <<: *defaults
  database: whathappened-dev

test:
  <<: *defaults
  database: whathappened-test

production:
  <<: *defaults
  database: whathappened-test

