staging:
  aws_access_key: AKIAITQWVME6VRL6MI7A
  aws_secret_access_key: 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
  bucket_base_name: horizon_trackable_tableware

production:
  aws_access_key: AKIAITQWVME6VRL6MI7A
  aws_secret_access_key: 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
  bucket_base_name: horizon_trackable_tableware
