--- 
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: socksforlife.co.uk
  external_host: ec2-50-16-109-86.compute-1.amazonaws.com
  external_ip: 50.16.109.86
  image_id: ami-ccf405a5
  image_type: m1.small
  instance_id: i-742f1e16
  internal_host: ip-10-12-102-228.ec2.internal
  internal_ip: 10.12.102.228
  name: production
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web_tools
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: xmpp
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: 
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql_master
    options: {}

  root_device_type: ebs
  security_groups: 
  - whathappened_production_default
  - whathappened_production_xmpp
  - whathappened_production_web
  - whathappened_production_web_tools
  - whathappened_production_production
  - whathappened_production_haproxy
  - whathappened_production_app
  - whathappened_production_passenger
  - whathappened_production_apache
  - whathappened_production_db
  - whathappened_production_mysql_master
  zone: us-east-1b
- volumes: {}

  static_ips: {}

